learning_project/basic_app/urls.py
from django.urls import path
from basic_app import views

#template_urls

app_name='basic_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
]

learning_project/learning_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic_app.urls')),
    
]

learning_project/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)

    portfolia_site=models.URLField(blank=True)

    profile_pic=models.ImageField(upload_to='profile_pic',blank=True)


    def __str__(self):
        return self.user.username

learning_project/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model=User
        fields=('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model=UserProfileInfo

        fields=('portfolia_site','profile_pic')

learning_project/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

# Create your views here.
def index(request):
    return render(request,'basic_app/index.html')

def register(request):


    registered=False

    if request.method == 'POST':
        user_form=UserForm(data=request.POST)
        profile_form=UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():

            user=user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                print('found it')

            profile.save()

            registered=True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'basic_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

learning_project/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <title>Django Framwork</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

<head>
  <meta charset="utf-8">
  <title></title>
  <!-- BootStarp Css and Js -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

</head>

<body>
  <!-- website main title and logo -->
  <div class="container-fluid bg-primary text-white">
    <h1> Django Test Site </h1>
  </div>

  <!-- Navigation bar -->
  <div class="container">
    <ul class="nav nav-pills nav-justified">
      <li class="nav-item">
        <a class="nav-link active" href="{% url 'basic_app:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'basic_app:register' %}">Registration</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
          Settings
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Account Settings</a>
          {% if user.is_authenticated %}
          <a class="dropdown-item" href="#">Logout</a>
          {% else %}
          <a class="dropdown-item" href="#">Log IN </a>
          {% endif %}
        </div>
    </ul><br>
  </div>


{% if user.is_authenticated%}
  <div class="container">
    {% block body_block %}
    {% endblock %}
{% else %}
  <div class="container">
      <h2>You are not login Now.</h2>
  </div>
{% endif %}

  </div>

</body>

</html>

learning_project/basic_app/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

 <div class="container">
   <div class="jumbotron">

   <h1>This Site is Devloped Under Django FrameWork.</h1>
 </div>
 <div class="jumbotron">
 <p>Django is a Python-based free and open-source web framework, which follows the model-template-view architectural
   pattern. It is maintained by the Django Software Foundation, an independent organization established as a 501
   non-profit. Django's primary goal is to ease the creation of complex, database-driven websites. Check<a
     href="https://docs.djangoproject.com/"> Django Documentaion</a> for more information.</p>
     </div>
{% endblock %}

learning_project/basic_app/templates/basic_app/login.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                {{ form| crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Login</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need An Account? <a class="ml-2" href="{% url 'register' %}">Sign Up Now</a>
            </small>
        </div>
    </div>
{% endblock content %}

learning_project/basic_app/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load static %}
{% block body_block %}
{% load crispy_forms_tags %}

<div class="jumbotron">
  <h1>Register here</h1>
  <h3>Fill out the form:</h3>
  <form enctype="multipart/form_data" method="POST">

     {% csrf_token %}
     {{ user_form| crispy }}
     {{ profile_form| crispy }}
     <input type="submit" name="" value="Register">

  </form>

</div>




{% endblock %}